apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  type: NodePort # Disaridan erisim icin kapi aciyoruz
  ports:
  - port: 5000
    targetPort: 80
    nodePort: 31000 
    name: vote
  selector:
    app: vote

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deploy
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
	imagePullSecrets:      
      	- name: regcred
      containers:
      - name: vote
        image: mturkkan/voting-app-vote:latest
        imagePullPolicy: IfNotPresent
env:
        - name: OPTION_A
          value: "Galatasaray"
        - name: OPTION_B
          value: "Fenerbahce"
        ports:
        - containerPort: 80
          name: vote
